return {
  {
    'nvim-treesitter/nvim-treesitter',
    dependencies = {
      'nvim-treesitter/nvim-treesitter-textobjects',
    },
    branch = 'master',
    lazy = false,
    build = ':TSUpdate',
    opts = {
      auto_install = true,
      highlight = { enable = true },
      indent = { enable = true },
      ensure_installed = {
        'bash',
        'c',
        'css',
        'diff',
        'html',
        'javascript',
        'jsdoc',
        'json',
        'jsonc',
        'lua',
        'luadoc',
        'luap',
        'markdown',
        'markdown_inline',
        'php',
        'printf',
        'python',
        'query',
        'regex',
        'scss',
        'sql',
        'toml',
        'tsx',
        'tmux',
        'typescript',
        'vim',
        'vimdoc',
        'xml',
        'yaml',
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          node_incremental = 'v',
          node_decremental = 'V',
        },
      },
      textobjects = {
        select = {
          enable = true,
          lookahead = true,
          keymaps = {
            ['af'] = { query = '@function.outer', desc = 'select around function' },
            ['if'] = { query = '@function.inner', desc = 'select inner function' },
            ['ac'] = { query = '@class.outer', desc = 'select around class' },
            ['ic'] = { query = '@class.inner', desc = 'select inner part of a class region' },
            ['as'] = { query = '@local.scope', query_group = 'locals', desc = 'select language scope' },
            ['ia'] = { query = '@parameter.inner', desc = 'select inner parameter' },
            ['aa'] = { query = '@parameter.outer', desc = 'select around parameter (with commas)' },
          },
        },
      },
    },
    config = function(_, opts)
      require('nvim-treesitter.configs').setup(opts)
    end,
  },
}
